style: changes the layout to grid
coding-bootcamps-eu/final-project-2023-06 pull request #7
Opened 2023-09-20 11:41 UTC by Beggsn

Kannst du bitte mal über das CSS gehen und ggf. Verbesserungen vorschlagen?
Das Grid ist noch nicht so schön.
Zum Beispiel sind die Bilder zu gestaucht, da sie unterschiedliche Größen haben, wäre schöner, wenn ihre Boxen etwas größer wären.
Dir fällt bestimmt noch mehr auf.

2023-09-20 15:34 UTC, gabrielheinrich requested changes

2023-09-20 15:34 UTC, gabrielheinrich commented on src/views/TemplateView.vue
> +  grid-auto-rows: var(--row-height);
Nimm die row height lieber raus, dann können die Bilder selbst die höhe bestimmen und du bekommst keine Überlappungen von den Überschriften der nächsten zeile

2023-09-20 15:34 UTC, gabrielheinrich commented on src/views/TemplateView.vue
> +  object-fit: cover;
object-fit: contain, ist wahrscheinlich besser, damit man das gesamte Meme sieht.

2023-09-20 15:34 UTC, gabrielheinrich commented on src/views/TemplateView.vue
> +  transition: 0.5s ease-in-out;
Warum setzt du eine transition?

2023-09-20 15:34 UTC, gabrielheinrich commented on src/views/TemplateView.vue
> +  }
Anstelle die column anzahl an breakpoints anzugeben, könntest du auch mit auto-fit arbeiten,
d.h. oben ` grid-template-columns: repeat(auto-fit, minmax(240px, 1fr))`

2023-09-20 15:42 UTC, gabrielheinrich commented on src/views/TemplateView.vue
> +  }
https://kulturbanause.de/blog/css-grid-auto-fill-responsive-layouts-ohne-media-queries/

2023-09-21 10:06 UTC, Beggsn commented on src/views/TemplateView.vue
> +  grid-auto-rows: var(--row-height);
erledigt

2023-09-21 10:06 UTC, Beggsn commented on src/views/TemplateView.vue
> +  object-fit: cover;
erledigt

2023-09-21 10:07 UTC, Beggsn commented on src/views/TemplateView.vue
> +  transition: 0.5s ease-in-out;
erledigt

2023-09-21 10:07 UTC, Beggsn commented on src/views/TemplateView.vue
> +  }
erledigt

2023-09-21 12:23 UTC, gabrielheinrich approved these changes

2023-09-21 12:26 UTC, merged